AllCops:
  UseCache: false
  TargetRubyVersion: 2.3
  Exclude:
    - 'config/unicorn.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'config/puma.rb'

Metrics/BlockLength:
  Max: 60

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Max: 60

PredicateName:
  NamePrefix:
    - is_
    - has_
    - have_

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '()'
    '%i': '()'
    '%q': '()'
    '%Q': '()'
    '%r': '{}'
    '%s': '()'
    '%w': '()'
    '%W': '()'
    '%x': '()'

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false


inherit_from: .rubocop_todo.yml
